// <auto-generated />
namespace BOL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UploadPLNDELVtoPendDocRtn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UploadPLNDELVtoPendDocRtn));
        
        string IMigrationMetadata.Id
        {
            get { return "201611210224013_Upload PLNDELV-to-PendDocRtn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
