// <auto-generated />
namespace BOL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class repending : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repending));
        
        string IMigrationMetadata.Id
        {
            get { return "201607040714486_re-pending"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
