namespace BOL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class chg_28102016 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AcceptedAdjusteds", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.AcceptedAdjusteds", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.AcceptedDelays", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.AcceptedDelays", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.AcceptPendings", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.AcceptPendings", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.DocReturnAdjusteds", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.DocReturnAdjusteds", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.DocReturnDelays", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.DocReturnDelays", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.DocReturnPendings", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.DocReturnPendings", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.InboundAdjusteds", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.InboundAdjusteds", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.InboundDelays", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.InboundDelays", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.InboundPendings", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.InboundPendings", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAcceptMonths", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAcceptMonths", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAccepts", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAccepts", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAcceptYears", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAcceptYears", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAdjusteds", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeAdjusteds", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDelays", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDelays", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDeliveries", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDeliveries", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDeliveryMonths", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDeliveryMonths", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDeliveryYears", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDeliveryYears", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDocReturnMonths", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDocReturnMonths", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDocReturns", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDocReturns", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDocReturnYears", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeDocReturnYears", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeInboundMonths", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeInboundMonths", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeInbounds", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeInbounds", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeInboundYears", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeInboundYears", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeOutboundMonths", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeOutboundMonths", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeOutbounds", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeOutbounds", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeOutboundYears", "Segment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeOutboundYears", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimePendings", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimePendings", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeTenderMonths", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeTenders", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OntimeTenderYears", "SubSegment", c => c.String(maxLength: 20));
            AddColumn("dbo.OutboundAdjusteds", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OutboundAdjusteds", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OutboundDelays", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OutboundDelays", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OutboundPendings", "SEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.OutboundPendings", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.TenderedAdjusteds", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.TenderedDelays", "SUBSEGMENT", c => c.String(maxLength: 20));
            AddColumn("dbo.TenderPendings", "SUBSEGMENT", c => c.String(maxLength: 20));
            CreateIndex("dbo.AcceptedAdjusteds", "SEGMENT");
            CreateIndex("dbo.AcceptedDelays", "SEGMENT");
            CreateIndex("dbo.AcceptPendings", "SEGMENT");
            CreateIndex("dbo.DocReturnAdjusteds", "SEGMENT");
            CreateIndex("dbo.DocReturnDelays", "SEGMENT");
            CreateIndex("dbo.DocReturnPendings", "SEGMENT");
            CreateIndex("dbo.InboundAdjusteds", "SEGMENT");
            CreateIndex("dbo.InboundDelays", "SEGMENT");
            CreateIndex("dbo.InboundPendings", "SEGMENT");
            CreateIndex("dbo.OntimeAdjusteds", "SEGMENT");
            CreateIndex("dbo.OntimeDelays", "SEGMENT");
            CreateIndex("dbo.OntimePendings", "SEGMENT");
            CreateIndex("dbo.OutboundAdjusteds", "SEGMENT");
            CreateIndex("dbo.OutboundDelays", "SEGMENT");
            CreateIndex("dbo.OutboundPendings", "SEGMENT");
        }
        
        public override void Down()
        {
            DropIndex("dbo.OutboundPendings", new[] { "SEGMENT" });
            DropIndex("dbo.OutboundDelays", new[] { "SEGMENT" });
            DropIndex("dbo.OutboundAdjusteds", new[] { "SEGMENT" });
            DropIndex("dbo.OntimePendings", new[] { "SEGMENT" });
            DropIndex("dbo.OntimeDelays", new[] { "SEGMENT" });
            DropIndex("dbo.OntimeAdjusteds", new[] { "SEGMENT" });
            DropIndex("dbo.InboundPendings", new[] { "SEGMENT" });
            DropIndex("dbo.InboundDelays", new[] { "SEGMENT" });
            DropIndex("dbo.InboundAdjusteds", new[] { "SEGMENT" });
            DropIndex("dbo.DocReturnPendings", new[] { "SEGMENT" });
            DropIndex("dbo.DocReturnDelays", new[] { "SEGMENT" });
            DropIndex("dbo.DocReturnAdjusteds", new[] { "SEGMENT" });
            DropIndex("dbo.AcceptPendings", new[] { "SEGMENT" });
            DropIndex("dbo.AcceptedDelays", new[] { "SEGMENT" });
            DropIndex("dbo.AcceptedAdjusteds", new[] { "SEGMENT" });
            DropColumn("dbo.TenderPendings", "SUBSEGMENT");
            DropColumn("dbo.TenderedDelays", "SUBSEGMENT");
            DropColumn("dbo.TenderedAdjusteds", "SUBSEGMENT");
            DropColumn("dbo.OutboundPendings", "SUBSEGMENT");
            DropColumn("dbo.OutboundPendings", "SEGMENT");
            DropColumn("dbo.OutboundDelays", "SUBSEGMENT");
            DropColumn("dbo.OutboundDelays", "SEGMENT");
            DropColumn("dbo.OutboundAdjusteds", "SUBSEGMENT");
            DropColumn("dbo.OutboundAdjusteds", "SEGMENT");
            DropColumn("dbo.OntimeTenderYears", "SubSegment");
            DropColumn("dbo.OntimeTenders", "SubSegment");
            DropColumn("dbo.OntimeTenderMonths", "SubSegment");
            DropColumn("dbo.OntimePendings", "SUBSEGMENT");
            DropColumn("dbo.OntimePendings", "SEGMENT");
            DropColumn("dbo.OntimeOutboundYears", "SubSegment");
            DropColumn("dbo.OntimeOutboundYears", "Segment");
            DropColumn("dbo.OntimeOutbounds", "SubSegment");
            DropColumn("dbo.OntimeOutbounds", "Segment");
            DropColumn("dbo.OntimeOutboundMonths", "SubSegment");
            DropColumn("dbo.OntimeOutboundMonths", "Segment");
            DropColumn("dbo.OntimeInboundYears", "SubSegment");
            DropColumn("dbo.OntimeInboundYears", "Segment");
            DropColumn("dbo.OntimeInbounds", "SubSegment");
            DropColumn("dbo.OntimeInbounds", "Segment");
            DropColumn("dbo.OntimeInboundMonths", "SubSegment");
            DropColumn("dbo.OntimeInboundMonths", "Segment");
            DropColumn("dbo.OntimeDocReturnYears", "SubSegment");
            DropColumn("dbo.OntimeDocReturnYears", "Segment");
            DropColumn("dbo.OntimeDocReturns", "SubSegment");
            DropColumn("dbo.OntimeDocReturns", "Segment");
            DropColumn("dbo.OntimeDocReturnMonths", "SubSegment");
            DropColumn("dbo.OntimeDocReturnMonths", "Segment");
            DropColumn("dbo.OntimeDeliveryYears", "SubSegment");
            DropColumn("dbo.OntimeDeliveryYears", "Segment");
            DropColumn("dbo.OntimeDeliveryMonths", "SubSegment");
            DropColumn("dbo.OntimeDeliveryMonths", "Segment");
            DropColumn("dbo.OntimeDeliveries", "SubSegment");
            DropColumn("dbo.OntimeDeliveries", "Segment");
            DropColumn("dbo.OntimeDelays", "SUBSEGMENT");
            DropColumn("dbo.OntimeDelays", "SEGMENT");
            DropColumn("dbo.OntimeAdjusteds", "SUBSEGMENT");
            DropColumn("dbo.OntimeAdjusteds", "SEGMENT");
            DropColumn("dbo.OntimeAcceptYears", "SubSegment");
            DropColumn("dbo.OntimeAcceptYears", "Segment");
            DropColumn("dbo.OntimeAccepts", "SubSegment");
            DropColumn("dbo.OntimeAccepts", "Segment");
            DropColumn("dbo.OntimeAcceptMonths", "SubSegment");
            DropColumn("dbo.OntimeAcceptMonths", "Segment");
            DropColumn("dbo.InboundPendings", "SUBSEGMENT");
            DropColumn("dbo.InboundPendings", "SEGMENT");
            DropColumn("dbo.InboundDelays", "SUBSEGMENT");
            DropColumn("dbo.InboundDelays", "SEGMENT");
            DropColumn("dbo.InboundAdjusteds", "SUBSEGMENT");
            DropColumn("dbo.InboundAdjusteds", "SEGMENT");
            DropColumn("dbo.DocReturnPendings", "SUBSEGMENT");
            DropColumn("dbo.DocReturnPendings", "SEGMENT");
            DropColumn("dbo.DocReturnDelays", "SUBSEGMENT");
            DropColumn("dbo.DocReturnDelays", "SEGMENT");
            DropColumn("dbo.DocReturnAdjusteds", "SUBSEGMENT");
            DropColumn("dbo.DocReturnAdjusteds", "SEGMENT");
            DropColumn("dbo.AcceptPendings", "SUBSEGMENT");
            DropColumn("dbo.AcceptPendings", "SEGMENT");
            DropColumn("dbo.AcceptedDelays", "SUBSEGMENT");
            DropColumn("dbo.AcceptedDelays", "SEGMENT");
            DropColumn("dbo.AcceptedAdjusteds", "SUBSEGMENT");
            DropColumn("dbo.AcceptedAdjusteds", "SEGMENT");
        }
    }
}
