namespace BOL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class salesaspect : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.OntimeAcceptMonths", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeAcceptMonths", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeAcceptMonths", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeAcceptMonths", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeAccepts", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeAccepts", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeAccepts", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeAccepts", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeAcceptYears", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeAcceptYears", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeAcceptYears", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeAcceptYears", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDeliveries", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDeliveries", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDeliveries", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDeliveries", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDeliveryMonths", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDeliveryMonths", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDeliveryMonths", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDeliveryMonths", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDeliveryYears", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDeliveryYears", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDeliveryYears", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDeliveryYears", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDocReturnMonths", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDocReturnMonths", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDocReturnMonths", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDocReturnMonths", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDocReturns", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDocReturns", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDocReturns", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDocReturns", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDocReturnYears", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDocReturnYears", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeDocReturnYears", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeDocReturnYears", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeInboundMonths", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeInboundMonths", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeInboundMonths", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeInboundMonths", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeInbounds", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeInbounds", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeInbounds", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeInbounds", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeInboundYears", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeInboundYears", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeInboundYears", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeInboundYears", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeOutboundMonths", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeOutboundMonths", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeOutboundMonths", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeOutboundMonths", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeOutbounds", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeOutbounds", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeOutbounds", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeOutbounds", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeOutboundYears", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeOutboundYears", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeOutboundYears", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeOutboundYears", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeTenderMonths", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeTenderMonths", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeTenderMonths", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeTenderMonths", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeTenders", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeTenders", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeTenders", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeTenders", "CarrierName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeTenderYears", "SoldToId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeTenderYears", "SoldToName", c => c.String(maxLength: 800));
            AddColumn("dbo.OntimeTenderYears", "CarrierId", c => c.String(maxLength: 10));
            AddColumn("dbo.OntimeTenderYears", "CarrierName", c => c.String(maxLength: 800));
        }
        
        public override void Down()
        {
            DropColumn("dbo.OntimeTenderYears", "CarrierName");
            DropColumn("dbo.OntimeTenderYears", "CarrierId");
            DropColumn("dbo.OntimeTenderYears", "SoldToName");
            DropColumn("dbo.OntimeTenderYears", "SoldToId");
            DropColumn("dbo.OntimeTenders", "CarrierName");
            DropColumn("dbo.OntimeTenders", "CarrierId");
            DropColumn("dbo.OntimeTenders", "SoldToName");
            DropColumn("dbo.OntimeTenders", "SoldToId");
            DropColumn("dbo.OntimeTenderMonths", "CarrierName");
            DropColumn("dbo.OntimeTenderMonths", "CarrierId");
            DropColumn("dbo.OntimeTenderMonths", "SoldToName");
            DropColumn("dbo.OntimeTenderMonths", "SoldToId");
            DropColumn("dbo.OntimeOutboundYears", "CarrierName");
            DropColumn("dbo.OntimeOutboundYears", "CarrierId");
            DropColumn("dbo.OntimeOutboundYears", "SoldToName");
            DropColumn("dbo.OntimeOutboundYears", "SoldToId");
            DropColumn("dbo.OntimeOutbounds", "CarrierName");
            DropColumn("dbo.OntimeOutbounds", "CarrierId");
            DropColumn("dbo.OntimeOutbounds", "SoldToName");
            DropColumn("dbo.OntimeOutbounds", "SoldToId");
            DropColumn("dbo.OntimeOutboundMonths", "CarrierName");
            DropColumn("dbo.OntimeOutboundMonths", "CarrierId");
            DropColumn("dbo.OntimeOutboundMonths", "SoldToName");
            DropColumn("dbo.OntimeOutboundMonths", "SoldToId");
            DropColumn("dbo.OntimeInboundYears", "CarrierName");
            DropColumn("dbo.OntimeInboundYears", "CarrierId");
            DropColumn("dbo.OntimeInboundYears", "SoldToName");
            DropColumn("dbo.OntimeInboundYears", "SoldToId");
            DropColumn("dbo.OntimeInbounds", "CarrierName");
            DropColumn("dbo.OntimeInbounds", "CarrierId");
            DropColumn("dbo.OntimeInbounds", "SoldToName");
            DropColumn("dbo.OntimeInbounds", "SoldToId");
            DropColumn("dbo.OntimeInboundMonths", "CarrierName");
            DropColumn("dbo.OntimeInboundMonths", "CarrierId");
            DropColumn("dbo.OntimeInboundMonths", "SoldToName");
            DropColumn("dbo.OntimeInboundMonths", "SoldToId");
            DropColumn("dbo.OntimeDocReturnYears", "CarrierName");
            DropColumn("dbo.OntimeDocReturnYears", "CarrierId");
            DropColumn("dbo.OntimeDocReturnYears", "SoldToName");
            DropColumn("dbo.OntimeDocReturnYears", "SoldToId");
            DropColumn("dbo.OntimeDocReturns", "CarrierName");
            DropColumn("dbo.OntimeDocReturns", "CarrierId");
            DropColumn("dbo.OntimeDocReturns", "SoldToName");
            DropColumn("dbo.OntimeDocReturns", "SoldToId");
            DropColumn("dbo.OntimeDocReturnMonths", "CarrierName");
            DropColumn("dbo.OntimeDocReturnMonths", "CarrierId");
            DropColumn("dbo.OntimeDocReturnMonths", "SoldToName");
            DropColumn("dbo.OntimeDocReturnMonths", "SoldToId");
            DropColumn("dbo.OntimeDeliveryYears", "CarrierName");
            DropColumn("dbo.OntimeDeliveryYears", "CarrierId");
            DropColumn("dbo.OntimeDeliveryYears", "SoldToName");
            DropColumn("dbo.OntimeDeliveryYears", "SoldToId");
            DropColumn("dbo.OntimeDeliveryMonths", "CarrierName");
            DropColumn("dbo.OntimeDeliveryMonths", "CarrierId");
            DropColumn("dbo.OntimeDeliveryMonths", "SoldToName");
            DropColumn("dbo.OntimeDeliveryMonths", "SoldToId");
            DropColumn("dbo.OntimeDeliveries", "CarrierName");
            DropColumn("dbo.OntimeDeliveries", "CarrierId");
            DropColumn("dbo.OntimeDeliveries", "SoldToName");
            DropColumn("dbo.OntimeDeliveries", "SoldToId");
            DropColumn("dbo.OntimeAcceptYears", "CarrierName");
            DropColumn("dbo.OntimeAcceptYears", "CarrierId");
            DropColumn("dbo.OntimeAcceptYears", "SoldToName");
            DropColumn("dbo.OntimeAcceptYears", "SoldToId");
            DropColumn("dbo.OntimeAccepts", "CarrierName");
            DropColumn("dbo.OntimeAccepts", "CarrierId");
            DropColumn("dbo.OntimeAccepts", "SoldToName");
            DropColumn("dbo.OntimeAccepts", "SoldToId");
            DropColumn("dbo.OntimeAcceptMonths", "CarrierName");
            DropColumn("dbo.OntimeAcceptMonths", "CarrierId");
            DropColumn("dbo.OntimeAcceptMonths", "SoldToName");
            DropColumn("dbo.OntimeAcceptMonths", "SoldToId");
        }
    }
}
