//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCGLKPIUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCGLKPIEntities : DbContext
    {
        public SCGLKPIEntities()
            : base("name=SCGLKPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_ontime_accept_Result> sp_ontime_accept(string datestart, string datestop)
        {
            var datestartParameter = datestart != null ?
                new ObjectParameter("Datestart", datestart) :
                new ObjectParameter("Datestart", typeof(string));
    
            var datestopParameter = datestop != null ?
                new ObjectParameter("Datestop", datestop) :
                new ObjectParameter("Datestop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ontime_accept_Result>("sp_ontime_accept", datestartParameter, datestopParameter);
        }
    
        public virtual ObjectResult<sp_ontime_tender_Result> sp_ontime_tender(Nullable<System.DateTime> datestart, Nullable<System.DateTime> datestop)
        {
            var datestartParameter = datestart.HasValue ?
                new ObjectParameter("Datestart", datestart) :
                new ObjectParameter("Datestart", typeof(System.DateTime));
    
            var datestopParameter = datestop.HasValue ?
                new ObjectParameter("Datestop", datestop) :
                new ObjectParameter("Datestop", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ontime_tender_Result>("sp_ontime_tender", datestartParameter, datestopParameter);
        }
    }
}
